### ISSUE TITLE
Make curl invocations reliable

### ISSUE THREAD

**Issue by syedriko** [redhat-developer-demos/knative-tutorial#96] opened 2019-03-31 02:19 UTC
**Describe the bug**
In Build Template
curl -H "Host: event-greeter.knativetutorial.example.com" $IP_ADDRESS \
   -H "Content-Type: application/json" \
   -d '{"message": "test message"}'
The above command produces no output and returns 0 for an exit code. A repeated invocation works fine and produces the expected result. It seems like a timeout on the curl part due to the target pod taking its time to spin up.

**To Reproduce**
Run the curl command in the Build Template chapter of the tutorial.

**Expected behavior**
curl makes a successful invocation every time.

**Desktop (please complete the following information):**
 - OS: Fedora 29

**Comment by kameshsampath** [comment] 2019-04-01 10:55
the services does have liveliness and readiness probes add to avoid this empty result or HTTP 502.  but i will be soon moving examples to use Quarkus so we should see faster boot up. 

@markusthoemmes  - any thoughts ?

**Comment by markusthoemmes** [comment] 2019-04-01 11:18
It'd be interesting to know what response codes are returned. @syedriko could you add the `-v` flag to your curl command to get that?

You might see 404s briefly after your service becomes ready which equates to Istio's propagation delay. We've got an item to fix that on our backlog, although it's not high prio atm and there's also no plan as to how to fix it currently.

**Comment by syedriko** [comment] 2019-04-01 21:27
Here you go:
- without -v
```
[syedriko@localhost knative]$ curl -H "Host: event-greeter.knativetutorial.example.com" $IP_ADDRESS -H "Content-Type: application/json" -d '{"message": "test message"}'
[syedriko@localhost knative]$ echo $?
0
[syedriko@localhost knative]$
```
- with -v
```
[syedriko@localhost knative]$ curl -v -H "Host: event-greeter.knativetutorial.example.com" $IP_ADDRESS -H "Content-Type: application/json" -d '{"message": "test message"}'
* Rebuilt URL to: 192.168.39.2:31380/
*   Trying 192.168.39.2...
* TCP_NODELAY set
* Connected to 192.168.39.2 (192.168.39.2) port 31380 (#0)
> POST / HTTP/1.1
> Host: event-greeter.knativetutorial.example.com
> User-Agent: curl/7.61.1
> Accept: */*
> Content-Type: application/json
> Content-Length: 27
> 
* upload completely sent off: 27 out of 27 bytes
< HTTP/1.1 404 Not Found
< location: http://event-greeter.knativetutorial.example.com/
< date: Mon, 01 Apr 2019 21:23:38 GMT
< server: envoy
< connection: close
< content-length: 0
< 
* Closing connection 0
[syedriko@localhost knative]$ echo $?
0
[syedriko@localhost knative]$ 
```
Now thinking about it, may be running curl with -v is the way to go. It makes it clear what's going on instead of just exiting silently and we can explain in the tutorial that it's normal to see 404s for a while (is it?) but that the invocation will eventually succeed.

**Comment by markusthoemmes** [comment] 2019-04-02 06:00
@syedriko yes, for now the 404s are "works as intended" (they are also retried by upstream's e2e tests). https://github.com/knative/serving/issues/3312 captures the requirement.

**Comment by kameshsampath** [comment] 2019-04-16 02:30
@syedriko  - if this expected behaviour then shall we close this bug?

**Comment by syedriko** [comment] 2019-04-16 05:09
I suppose we can, as long as we explain in the text that a curl invocation can produce no output and the student may need to repeat it until it succeeds?

**Closed as completed** 2019-06-06 11:56 UTC
Labels: demo-src
