### ISSUE TITLE
Knative Revision Delete should not suggest removing current revisions

### ISSUE THREAD

**Issue by maschmid** [redhat-developer-demos/knative-tutorial#210] opened 2020-03-23 19:58 UTC
**Describe the bug**
The tutorial suggests deleting the current revision and says that this will revert the state to the previous revision. Such behaviour is not defined, and doesn't work that way in current knative serving (as of Serverless 1.5.0)

"kn revision delete" should perhaps be used to delete the old revision instead.

**To Reproduce**
Follow the tutorial with Serverless 1.5.0 installed, up to https://redhat-developer-demos.github.io/knative-tutorial/knative-tutorial-serving/knative-client.html#kn-revisions-delete 

Notice the revision will be automatically restored when deleting the current revision.

**Comment by sebastienblanc** [comment] 2020-04-08 17:58
Hi, could you describe what would be the right behaviour , I'm not sure to fully understand what the problem is. Thanks :)

**Comment by kameshsampath** [comment] 2020-11-10 13:53
fixed in the upcoming release

**Closed as completed by kameshsampath** 2020-11-10 13:53 UTC
